---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  api/cities:
    get:
      summary: Retrieves cities
      tags:
      - Cities
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
        '404':
          description: pet not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
